#!/usr/bin/perl

use FindBin;
use File::Spec;

my ($volume, $directory, $file) = File::Spec->splitpath(__FILE__);

print $volume, $directory, $file, "\n"; 

print __FILE__;

print "the directory of my script is: " . $FindBin::Bin . "\n";

